
services:
    publisher:
        build: ./ig-poster
        ports:
            - "8080:3000"
        restart: always

    web-cli:
        build: ./interface
        ports:
            - "8000:3000"
        restart: always