name: Daily Publication

on: workflow_dispatch
#  schedule:
#    # every morning 8am
#    - cron:  '0 8 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      run: echo "node main.js ${{ secrets.NASA_TOKEN }} ${{ secrets.IG_TOKEN }}
