name: Daily Publication

on: workflow_dispatch
#  schedule:
#    # every morning 8am
#    - cron:  '0 8 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4
    - name: Checking context
      run: ls -alth; pwd; node -v; echo "Test secret access ${{ secrets.TEST }}"
    - name: Publish
      #run: node test.js "coucouuuuu"
      run: node main.js ${{ secrets.NASA_TOKEN }} ${{ secrets.IG_TOKEN }}
