name: Daily Publication

on:
  schedule:
    # every morning 8am
    - cron:  '0 8 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v4
    - name: Publish
      run: node main.js ${{ secrets.NASA_TOKEN }} ${{ secrets.IG_TOKEN }}
